# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\forms\reader_images.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 900)
        MainWindow.setMinimumSize(QtCore.QSize(800, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_control = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_control.sizePolicy().hasHeightForWidth())
        self.widget_control.setSizePolicy(sizePolicy)
        self.widget_control.setObjectName("widget_control")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_control)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_upload = QtWidgets.QPushButton(self.widget_control)
        self.btn_upload.setObjectName("btn_upload")
        self.horizontalLayout.addWidget(self.btn_upload)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_back = QtWidgets.QPushButton(self.widget_control)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.btn_next = QtWidgets.QPushButton(self.widget_control)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.verticalLayout.addWidget(self.widget_control)
        self.widget_reader = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_reader.sizePolicy().hasHeightForWidth())
        self.widget_reader.setSizePolicy(sizePolicy)
        self.widget_reader.setObjectName("widget_reader")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_reader)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_reader = QtWidgets.QLabel(self.widget_reader)
        self.label_reader.setText("")
        self.label_reader.setObjectName("label_reader")
        self.horizontalLayout_2.addWidget(self.label_reader)
        self.verticalLayout.addWidget(self.widget_reader)
        self.widget_page_number = QtWidgets.QWidget(self.centralwidget)
        self.widget_page_number.setObjectName("widget_page_number")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_page_number)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_page = QtWidgets.QLabel(self.widget_page_number)
        self.label_page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_page.setText("")
        self.label_page.setAlignment(QtCore.Qt.AlignCenter)
        self.label_page.setObjectName("label_page")
        self.horizontalLayout_3.addWidget(self.label_page)
        self.verticalLayout.addWidget(self.widget_page_number)
        self.widget_control.raise_()
        self.widget_reader.raise_()
        self.widget_page_number.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pdf reader"))
        self.btn_upload.setText(_translate("MainWindow", "Загрузить"))
        self.btn_back.setText(_translate("MainWindow", "<<"))
        self.btn_next.setText(_translate("MainWindow", ">>"))
